package com.bjpowernode.crm.settings.mapper;

import com.bjpowernode.crm.settings.domain.DicValue;

import java.util.List;

public interface DicValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu May 21 09:23:58 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu May 21 09:23:58 CST 2020
     */
    int insert(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu May 21 09:23:58 CST 2020
     */
    int insertSelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu May 21 09:23:58 CST 2020
     */
    DicValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu May 21 09:23:58 CST 2020
     */
    int updateByPrimaryKeySelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu May 21 09:23:58 CST 2020
     */
    int updateByPrimaryKey(DicValue record);

    /**
     * 查询所有的数据字典值
     * @return
     *//*
    List<DicValue> selectAllDicValues();

    *//**
     * 保存创建的数据字典值
     * @param dicValue
     * @return
     *//*
    int insertDicValue(DicValue dicValue);

    *//**
    * 根据ids删除数据字典值
    *//*
    int deleteDicValueByIds(String[] ids);

    *//**
    * 根据id查询数据字典值
    *//*
    DicValue selectDicValueById(String id);

    *//**
    * 保存修改的数据字典值
    *//*
    int updateDicValue(DicValue dicValue);
    *//**
    *根据typeCodes删除这些类型下的所有数据字典值
    *//*
    int deleteDicValueByTypeCodes(String[] typeCodes);
    *//**
    * 根据typeCode查询数据字典值
    *//*
    List<DicValue> selectDicValueByTypeCode(String typeCode);*/


    //查询所有的字典值
    List<DicValue> selectAllDicVal();

    //根据id查询字典值
    DicValue selectDicValById(String id);

    //增加保存字典值
    int saveDicVal(DicValue dicValue);

    //批量删除字典值
    int deleteDicValBatch(String[] id);//这个的方法就是给删除字典类型时提供的，当字典类型删除时，首先要删除该字典类型下的所有的字典值

    //更新字典值
    int updateDicVal(DicValue dicValue);

    //根据typeCode删除这些类型下的所有数字的字典值
    int deleteDicValByTypeCodes(String[] typeCodes);

    //根据typeCode查询数据字典值
    List<DicValue> selectDicValByTypeCode(String typeCode);
}